#!groovy
pipeline {
    options { 
        buildDiscarder(logRotator(numToKeepStr: '7')) 
        skipDefaultCheckout() 
    }
	agent none
    stages {
        stage('Setup') {
			steps {
				script {
  					dockerBuildPublish {
						dockerHubCredentialsId = 'docker-hub-beedemo'
					}
				}
			}
		}
	}
}
